openapi: 3.2.0
info:
  version: v1
  title: Datto|Autotask PSA Rest Webhook Event Error Logs API
servers:
- url: https://webservices2.autotask.net/ATServicesRest
tags:
- name: WebhookEventErrorLogs
paths:
  /V1.0/WebhookEventErrorLogs/query:
    get:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_UrlParameterQuery
      parameters:
      - name: search
        in: query
        required: true
        schema:
          type: string
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryActionResult_WebhookEventErrorLogModel_WebhookEventErrorLog'
            text/json:
              schema:
                $ref: '#/components/schemas/QueryActionResult_WebhookEventErrorLogModel_WebhookEventErrorLog'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_Query
      parameters:
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryActionResult_WebhookEventErrorLogModel_WebhookEventErrorLog'
            text/json:
              schema:
                $ref: '#/components/schemas/QueryActionResult_WebhookEventErrorLogModel_WebhookEventErrorLog'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryModel'
        required: true
  /V1.0/WebhookEventErrorLogs/{id}:
    get:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_QueryItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemQueryResultModel_WebhookEventErrorLogModel_WebhookEventErrorLog'
            text/json:
              schema:
                $ref: '#/components/schemas/ItemQueryResultModel_WebhookEventErrorLogModel_WebhookEventErrorLog'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_DeleteEntity
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/OperationResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /V1.0/WebhookEventErrorLogs/query/count:
    get:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_UrlParameterQueryCount
      parameters:
      - name: search
        in: query
        required: true
        schema:
          type: string
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryCountResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/QueryCountResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_QueryCount
      parameters:
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryCountResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/QueryCountResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryModel'
        required: true
  /V1.0/WebhookEventErrorLogs/entityInformation:
    get:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_QueryEntityInformation
      parameters:
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityInformationResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/EntityInformationResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /V1.0/WebhookEventErrorLogs/entityInformation/fields:
    get:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_QueryFieldDefinitions
      parameters:
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldInformationResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/FieldInformationResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /V1.0/WebhookEventErrorLogs/entityInformation/userDefinedFields:
    get:
      tags:
      - WebhookEventErrorLogs
      operationId: WebhookEventErrorLogs_QueryUserDefinedFieldDefinitions
      parameters:
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDefinedFieldInformationResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/UserDefinedFieldInformationResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    UserDefinedFieldInformationResultModel:
      type: object
      properties:
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
            readOnly: true
    EntityInformationResultModel:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/EntityInformationModel'
          readOnly: true
    PagingModel:
      type: object
      properties:
        count:
          format: int32
          type: integer
        requestCount:
          format: int32
          type: integer
          readOnly: true
        prevPageUrl:
          type: string
        nextPageUrl:
          type: string
    FieldInformationModel:
      type: object
      properties:
        name:
          type: string
        dataType:
          type: string
        length:
          format: int32
          type: integer
        isRequired:
          type: boolean
        isReadOnly:
          type: boolean
        isQueryable:
          type: boolean
        isReference:
          type: boolean
        referenceEntityType:
          type: string
        isPickList:
          type: boolean
        picklistValues:
          type: array
          items:
            $ref: '#/components/schemas/PickListValue'
        picklistParentValueField:
          type: string
        isSupportedWebhookField:
          $ref: '#/components/schemas/Object'
    FieldInformationResultModel:
      type: object
      properties:
        fields:
          type: array
          items:
            $ref: '#/components/schemas/FieldInformationModel'
            readOnly: true
    QueryCountResultModel:
      type: object
      properties:
        queryCount:
          format: int32
          type: integer
    PickListValue:
      type: object
      properties:
        value:
          type: string
        label:
          type: string
        isDefaultValue:
          type: boolean
        sortOrder:
          format: int32
          type: integer
        parentValue:
          type: string
        isActive:
          type: boolean
        isSystem:
          type: boolean
    RestUserAccessLevel:
      type: object
      properties: {}
    QueryModel:
      type: object
      properties:
        maxRecords:
          format: int32
          type: integer
        includeFields:
          type: array
          items:
            type: string
        filter:
          type: array
          items:
            $ref: '#/components/schemas/Filter'
      example:
        MaxRecords: 10
        IncludeFields: []
        Filter:
        - op: gt
          field: id
          value: 0
          udf: false
          items: []
    Object:
      type: object
      properties: {}
    QueryActionResult_WebhookEventErrorLogModel_WebhookEventErrorLog:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/WebhookEventErrorLogModel'
        pageDetails:
          $ref: '#/components/schemas/PagingModel'
    ItemQueryResultModel_WebhookEventErrorLogModel_WebhookEventErrorLog:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/WebhookEventErrorLogModel'
    Field:
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        type:
          type: string
        length:
          format: int32
          type: integer
        description:
          type: string
        isRequired:
          type: boolean
        isReadOnly:
          type: boolean
        isQueryable:
          type: boolean
        isReference:
          type: boolean
        referenceEntityType:
          type: string
        isPickList:
          type: boolean
        picklistValues:
          type: array
          items:
            $ref: '#/components/schemas/PickListValue'
        picklistParentValueField:
          type: string
        defaultValue:
          type: string
        isSupportedWebhookField:
          $ref: '#/components/schemas/Object'
    EntityInformationModel:
      type: object
      properties:
        name:
          type: string
          readOnly: true
        canCreate:
          type: boolean
          readOnly: true
        canDelete:
          type: boolean
          readOnly: true
        canQuery:
          type: boolean
          readOnly: true
        canUpdate:
          type: boolean
          readOnly: true
        userAccessForCreate:
          $ref: '#/components/schemas/RestUserAccessLevel'
          readOnly: true
        userAccessForDelete:
          $ref: '#/components/schemas/RestUserAccessLevel'
          readOnly: true
        userAccessForQuery:
          $ref: '#/components/schemas/RestUserAccessLevel'
          readOnly: true
        userAccessForUpdate:
          $ref: '#/components/schemas/RestUserAccessLevel'
          readOnly: true
        hasUserDefinedFields:
          type: boolean
          readOnly: true
        supportsWebhookCallouts:
          type: boolean
          readOnly: true
    Filter:
      type: object
      properties:
        op:
          type: string
        field:
          type: string
        udf:
          type: boolean
        value:
          description: 'Can be either an Integer, String, Boolean, an Array of Integers, or an Array of Strings. '
          type: object
          properties: {}
        items:
          description: An Array of Filter objects
          type: array
          items:
            $ref: '#/components/schemas/Filter'
    OperationResultModel:
      type: object
      properties:
        itemId:
          $ref: '#/components/schemas/Object'
    WebhookEventErrorLogModel:
      type: object
      properties:
        id:
          format: int64
          type: integer
        accountWebhookID:
          format: int32
          type: integer
        contactWebhookID:
          format: int32
          type: integer
        createDateTime:
          format: date-time
          type: string
        errorMessage:
          type: string
        payload:
          type: string
        sequenceNumber:
          format: int32
          type: integer
