openapi: 3.2.0
info:
  version: v1
  title: Datto|Autotask PSA Rest Subscription Periods Child API
servers:
- url: https://webservices2.autotask.net/ATServicesRest
tags:
- name: SubscriptionPeriodsChild
paths:
  /V1.0/Subscriptions/{parentId}/Periods:
    get:
      tags:
      - SubscriptionPeriodsChild
      operationId: SubscriptionPeriodsChild_Query
      parameters:
      - name: parentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryActionResult_SubscriptionPeriodModel_SubscriptionPeriod'
            text/json:
              schema:
                $ref: '#/components/schemas/QueryActionResult_SubscriptionPeriodModel_SubscriptionPeriod'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /V1.0/Subscriptions/{parentId}/Periods/{id}:
    get:
      tags:
      - SubscriptionPeriodsChild
      operationId: SubscriptionPeriodsChild_QueryItem
      parameters:
      - name: parentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemQueryResultModel_SubscriptionPeriodModel_SubscriptionPeriod'
            text/json:
              schema:
                $ref: '#/components/schemas/ItemQueryResultModel_SubscriptionPeriodModel_SubscriptionPeriod'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /V1.0/Subscriptions/{parentId}/Periods/entityInformation:
    get:
      tags:
      - SubscriptionPeriodsChild
      operationId: SubscriptionPeriodsChild_QueryEntityInformation
      parameters:
      - name: parentId
        in: path
        required: true
        schema:
          type: string
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityInformationResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/EntityInformationResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /V1.0/Subscriptions/{parentId}/Periods/entityInformation/fields:
    get:
      tags:
      - SubscriptionPeriodsChild
      operationId: SubscriptionPeriodsChild_QueryFieldDefinitions
      parameters:
      - name: parentId
        in: path
        required: true
        schema:
          type: string
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldInformationResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/FieldInformationResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /V1.0/Subscriptions/{parentId}/Periods/entityInformation/userDefinedFields:
    get:
      tags:
      - SubscriptionPeriodsChild
      operationId: SubscriptionPeriodsChild_QueryUserDefinedFieldDefinitions
      parameters:
      - name: parentId
        in: path
        required: true
        schema:
          type: string
      - name: ApiIntegrationCode
        in: header
        description: API Integration Code
        required: true
        schema:
          type: string
      - name: UserName
        in: header
        description: User Name
        required: true
        schema:
          type: string
      - name: Secret
        in: header
        description: Secret
        required: true
        schema:
          type: string
      - name: ImpersonationResourceId
        in: header
        description: Impersonation Resource Key
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDefinedFieldInformationResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/UserDefinedFieldInformationResultModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    ItemQueryResultModel_SubscriptionPeriodModel_SubscriptionPeriod:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/SubscriptionPeriodModel'
    EntityInformationResultModel:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/EntityInformationModel'
          readOnly: true
    UserDefinedFieldInformationResultModel:
      type: object
      properties:
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
            readOnly: true
    FieldInformationModel:
      type: object
      properties:
        name:
          type: string
        dataType:
          type: string
        length:
          format: int32
          type: integer
        isRequired:
          type: boolean
        isReadOnly:
          type: boolean
        isQueryable:
          type: boolean
        isReference:
          type: boolean
        referenceEntityType:
          type: string
        isPickList:
          type: boolean
        picklistValues:
          type: array
          items:
            $ref: '#/components/schemas/PickListValue'
        picklistParentValueField:
          type: string
        isSupportedWebhookField:
          $ref: '#/components/schemas/Object'
    FieldInformationResultModel:
      type: object
      properties:
        fields:
          type: array
          items:
            $ref: '#/components/schemas/FieldInformationModel'
            readOnly: true
    PickListValue:
      type: object
      properties:
        value:
          type: string
        label:
          type: string
        isDefaultValue:
          type: boolean
        sortOrder:
          format: int32
          type: integer
        parentValue:
          type: string
        isActive:
          type: boolean
        isSystem:
          type: boolean
    Object:
      type: object
      properties: {}
    QueryActionResult_SubscriptionPeriodModel_SubscriptionPeriod:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SubscriptionPeriodModel'
        pageDetails:
          $ref: '#/components/schemas/PagingModel'
    Field:
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        type:
          type: string
        length:
          format: int32
          type: integer
        description:
          type: string
        isRequired:
          type: boolean
        isReadOnly:
          type: boolean
        isQueryable:
          type: boolean
        isReference:
          type: boolean
        referenceEntityType:
          type: string
        isPickList:
          type: boolean
        picklistValues:
          type: array
          items:
            $ref: '#/components/schemas/PickListValue'
        picklistParentValueField:
          type: string
        defaultValue:
          type: string
        isSupportedWebhookField:
          $ref: '#/components/schemas/Object'
    RestUserAccessLevel:
      type: object
      properties: {}
    EntityInformationModel:
      type: object
      properties:
        name:
          type: string
          readOnly: true
        canCreate:
          type: boolean
          readOnly: true
        canDelete:
          type: boolean
          readOnly: true
        canQuery:
          type: boolean
          readOnly: true
        canUpdate:
          type: boolean
          readOnly: true
        userAccessForCreate:
          $ref: '#/components/schemas/RestUserAccessLevel'
          readOnly: true
        userAccessForDelete:
          $ref: '#/components/schemas/RestUserAccessLevel'
          readOnly: true
        userAccessForQuery:
          $ref: '#/components/schemas/RestUserAccessLevel'
          readOnly: true
        userAccessForUpdate:
          $ref: '#/components/schemas/RestUserAccessLevel'
          readOnly: true
        hasUserDefinedFields:
          type: boolean
          readOnly: true
        supportsWebhookCallouts:
          type: boolean
          readOnly: true
    PagingModel:
      type: object
      properties:
        count:
          format: int32
          type: integer
        requestCount:
          format: int32
          type: integer
          readOnly: true
        prevPageUrl:
          type: string
        nextPageUrl:
          type: string
    SubscriptionPeriodModel:
      type: object
      properties:
        id:
          format: int64
          type: integer
        periodCost:
          format: double
          type: number
        periodDate:
          format: date-time
          type: string
        periodPrice:
          format: double
          type: number
        postedDate:
          format: date-time
          type: string
        purchaseOrderNumber:
          type: string
        subscriptionID:
          format: int32
          type: integer
        soapParentPropertyId:
          format: int64
          type: integer
          readOnly: true
