openapi: 3.2.0
info:
  title: BMS API 2.0 Service Categories API
  description: Documentation of APIs Version 2.0
  version: '2.0'
servers:
- url: https://api.bms.kaseya.com
security:
- bearerAuth: []
tags:
- name: ServiceCategories
paths:
  /v2/admin/finance/servicecategory/lookup:
    get:
      tags:
      - ServiceCategories
      operationId: GetServiceCategoriesLookup
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServiceCategoryLookupOutputDtoIEnumerableResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceCategoryLookupOutputDtoIEnumerableResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ServiceCategoryLookupOutputDtoIEnumerableResponse'
  /v2/admin/finance/servicecategory/{categoryId}/servicesubcategory/lookup:
    get:
      tags:
      - ServiceCategories
      operationId: GetServiceSubCategoriesLookup
      parameters:
      - name: categoryId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServiceCategoryLookupOutputDtoIEnumerableResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceCategoryLookupOutputDtoIEnumerableResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ServiceCategoryLookupOutputDtoIEnumerableResponse'
components:
  schemas:
    ErrorInfo:
      type: object
      properties:
        Code:
          type: integer
          format: int32
        Message:
          type:
          - string
          - 'null'
        Details:
          type:
          - string
          - 'null'
        StackStrace:
          type:
          - string
          - 'null'
        SubErrors:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    ServiceCategoryLookupOutputDto:
      type: object
      properties:
        Id:
          type: integer
          format: int32
        Name:
          type:
          - string
          - 'null'
      additionalProperties: false
    ServiceCategoryLookupOutputDtoIEnumerableResponse:
      type: object
      properties:
        Success:
          type: boolean
          readOnly: true
        Error:
          $ref: '#/components/schemas/ErrorInfo'
        Result:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceCategoryLookupOutputDto'
      additionalProperties: false
  securitySchemes:
    bearerAuth:
      type: http
      description: JWT Authorization header using the Bearer scheme.
      scheme: bearer
      bearerFormat: JWT
